name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-php:
    name: Build PHP
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ ubuntu-20.04, ubuntu-18.04 ]

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)

          gh auth login --with-token <<<$(echo ${{ secrets.PERSONAL_ACCESS_TOKEN }})
          gh auth status

          mkdir bin/
          echo "data for ${{ matrix.image }}" > bin/filename
          PHP_VERSION="7.4.21"
          echo "PHP_VERSION=$PHP_VERSION" >> $GITHUB_ENV
          # echo "*error" > install.log
          # exit 1
          zip -r bin-${{ matrix.image }}.zip bin/
          GITHUB_RELEASE_TAG="$PHP_VERSION@$COMMIT_SHA"
          gh release create "$GITHUB_RELEASE_TAG" --title "PHP $PHP_VERSION" --notes-file NOTES.md || echo Release already created
          gh release upload "$GITHUB_RELEASE_TAG" bin-${{ matrix.image }}.zip

      - uses: actions/upload-artifact@v2
        with:
          name: PHP ${{ env.PHP_VERSION }} for ${{ matrix.image }}
          path: |
            bin/
