name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-php:
    name: Build
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ windows-2016 ]

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\link.exe"

      - uses: actions/upload-artifact@v2
        with:
          name: PHP ${{ env.PHP_VERSION }} for ${{ matrix.image }}
          path: |
            bin/
