name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-php:
    name: Build
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ windows-2016, windows-2019, windows-2022 ]

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          set vswhere="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
          call %vswhere% -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find VC\Auxiliary\Build\vcvars64.bat
        shell: cmd
