name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-php:
    name: Build
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ ubuntu-20.04 ]

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          whoami
          ps axuww

