name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-php:
    name: Build
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ windows-2019 ]

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          Get-DnsClientServerAddress
          #Get-DnsClientCache
          Resolve-DnsName -Name google.com -Server 168.63.129.16

      - uses: actions/upload-artifact@v2
        with:
          name: PHP ${{ env.PHP_VERSION }} for ${{ matrix.image }}
          path: |
            bin/
